apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: newsletter-db
  labels:
    app.kubernetes.io/part-of: newsletter
spec:
  memory: 800Mi
  cpu: "0.8"
  # storageClassName: standard
  storageSize: 2G
  pgConfig:
    dbname: newsletter-db
    username: pgadmin
    appUser: pgappuser
