# https://backstage.io/docs/features/software-catalog/descriptor-format/
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: newsleter
  description: Newsletter Service Application
spec:
  owner: newsletter-team
  domain: ecommerce-marketplace
