# https://backstage.io/docs/features/software-catalog/descriptor-format/
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Newsletter Application
  description: The Newsletter Application is part of the eCommerce Marketplace and provides subscribed users with product and service updates.

  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=newsletter"
    'backstage.io/techdocs-ref': dir:.
spec:
  type: system
  owner: newsletter-team
  domain: ecommerce-marketplace
