
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: newsletter-subscription
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: newsletter
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/debug: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: newsletter-db
  build:
    env:
      - name: BP_JVM_VERSION
        value: "20"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/v3/api-docs"
        owner: newsletter-team
        system: newsletter-subscription
        lifecycle: experimental
        description: Newsletter Subscription Management REST API Service 
  source:
    git:
      ref:
        branch: main
      url: https://github.com/pivotal-sadubois/newsletter
      subPath: newsletter-subscription








      

      # docker login harbor.apps.tapmc.pcfsdu.com/ -u admin -p Password12345
      # docker login harbor.apps.tap.pcfsdu.com/ -u admin -p Password12345

      # tanzu apps workload -n newsletter tail newsletter-subscription --timestamp --since 1h
      # tanzu apps workload -n newsletter tail newsletter-subscription --timestamp --since 10m

      # tanzu apps workload get newsletter-subscription
      # kubectl config set-context --current --namespace=newsletter

      # SERVICE CLAIM
      # tanzu services classes list
      # tanzu services classes get postgresql-unmanaged 

      # tanzu service class-claim create newsletter-db --class postgresql-unmanaged --parameter storageGB=1 -n newsletter
      # tanzu services class-claims get newsletter-db -n newsletter
      # sdubois$ tanzu service resource-claims list
      # tanzu service resource-claims get newsletter-db-gk5gq

      # RABBIT-MQ
      # tanzu service class-claim create newsletter-tabbit --class rabbitmq-unmanaged -n newsletter
      # tanzu services class-claims get newsletter-tabbit --namespace newsletter

      
      # tanzu apps workload create tanzu-java-web-app \
      # --git-branch main \
      # --git-repo https://github.com/pivotal-sadubois/newsletter \
      #   --sub-path newsletter-subscription \
      #   --label apps.tanzu.vmware.com/has-tests=true \
      #   --label app.kubernetes.io/part-of=newsletter \
      #   --type web 
      

    
