apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: newsletter
  description: Newsletter Application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - resources/newsletter-database/newsletter-database.yaml
    - groups/newsletter-team.yaml
    - components/newsletter-db/newsletter-db.yaml
    - components/newsletter-subscription/newsletter-subscription.yaml
    - components/newsletter-ui/newsletter-ui.yaml
    - systems/newsleter.yaml 
    - domain/ecommerce-marketplace.yaml
#   - api/newsletter-subscription.yaml
