apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: newsletter-subscription
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=newsletter"
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: "https://vmware.wavefront.com/u/gdq77TV7mG?t=map-sales-sandbox"
      title: Dashboard
      icon: dashboard

spec:
  type: service
  lifecycle: experimental
  owner: newsletter-team
  system: newsletter
  domain: ecommerce-marketplace
  dependsOn:
    - resource:newsletter/newsletter-db
    - resource:default/postgres-operator
  providesApis:
    - newsletter-subscription-api
    - newsletter-subscription
    - newsletter/newsletter-subscription
