
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: user-profile-ui
  namespace: guestbook
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: guestbook
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/pivotal-sadubois/guestbook
