apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: newsletter-database-0
  description: VMware Tanzu SQL with Postgres database as persistent backend for the newsletter applicaiton
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=newsletter"
    'backstage.io/techdocs-ref': dir:../
spec:
  type: database
  owner: newsletter-team
  system: newsletter-database
